services:
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=silesra
      - POSTGRES_USER=silesra
      - POSTGRES_PASSWORD=silesra
    networks:
      - silesrabackend_my_network
    ports:
      - "5432:5432"
    restart: always
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - silesrabackend_my_network
    ports:
      - "8080:80"
    
  web:
    build: .
    image: silesralatest
    command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - ./backend:/code
      - ./media:/app/media
    ports:
      - "8888:8888"
    environment:
      - POSTGRES_NAME=silesra
      - POSTGRES_USER=silesra
      - POSTGRES_PASSWORD=silesra
      - POSTGRES_HOST=localhost
    depends_on:
      - db
    env_file:
      - .env   
    networks:
      - silesrabackend_my_network

networks:
  silesrabackend_my_network:
    external: true
