# Generated by Django 5.0.6 on 2025-01-25 16:16

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCommonProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, choices=[('Addis Ababa', 'Addis Ababa'), ('Amhara', 'Amhara')], max_length=50, null=True)),
                ('description', models.CharField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serviceimage', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='product_images')),
                ('image_url', models.JSONField()),
                ('fee_recipt', models.ImageField(blank=True, default='servicepayment.jpg', null=True, upload_to='Servicefee_images')),
                ('fee_recipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the location', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the location', max_digits=9, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServiceCommonProperty', to='products.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='itemcommonproperty',
            name='contact',
        ),
        migrations.AddField(
            model_name='itemcommonproperty',
            name='fee_recipt',
            field=models.ImageField(blank=True, default='payment.jpg', null=True, upload_to='Servicefee_images'),
        ),
        migrations.AddField(
            model_name='itemcommonproperty',
            name='fee_recipt_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itemcommonproperty',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='itemcommonproperty',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='itemcommonproperty',
            name='service_fee_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ServiceCommonProperty', to='products.banks'),
        ),
        migrations.AlterField(
            model_name='banks',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='housetype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='itemcommonproperty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemcommonproperty',
            name='productimage',
            field=models.FileField(blank=True, null=True, upload_to=products.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='itemcommonproperty',
            name='sell_or_rent',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemcommonproperty',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemcommonproperty', to='products.subcategory'),
        ),
        migrations.CreateModel(
            name='ServiceOrBusinesstype',
            fields=[
                ('servicecommonproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.servicecommonproperty')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            bases=('products.servicecommonproperty',),
        ),
        migrations.AddField(
            model_name='servicecommonproperty',
            name='service_fee_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Service_ServiceCommonProperty', to='products.banks'),
        ),
    ]
