# Generated by Django 5.0.6 on 2025-01-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_servicecommonproperty_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceOrBusinesstype',
        ),
    ]
