# Generated by Django 5.0.6 on 2025-02-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_house_license_alter_car_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='sell_or_rent',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='electronics',
            name='sell_or_rent',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fashion',
            name='sell_or_rent',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fashion',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], max_length=50, null=True),
        ),
    ]
