# Generated by Django 5.0.6 on 2025-02-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_accessory_sell_or_rent_electronics_sell_or_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefee',
            name='feeReciptImagePath',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='houseType',
            field=models.CharField(blank=True, choices=[('Condominium', 'Condominium'), ('Villa', 'Villa'), ('House G+', 'House G+'), ('Commercial', 'Commercial'), ('GuestHouse', 'GuestHouse'), ('Apartment', 'Apartment'), ('Warehouse', 'Warehouse'), ('Land', 'Land')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/'),
        ),
    ]
