"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent
env_path = BASE_DIR / '.env'
load_dotenv(dotenv_path=env_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '188.245.105.29']
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_NAME'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': 'db', 
        'PORT': 5432,
    }
}

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',  # Enable CORS handling
    'user_managment',
     'products',
     'item',
     'setting'
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=70),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'backend.urls'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
CORS_ALLOW_HEADERS = [
    'authorization',
    'content-type',
    'x-requested-with',
    'accept',
    'origin',
    'access-control-allow-origin',
]

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'user_managment.User'
# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'

# Correct STATIC_ROOT to ensure collected files go to staticfiles
STATIC_ROOT = BASE_DIR / 'staticfiles'  # D:\CSMS\csm\staticfiles

# Correct STATICFILES_DIRS to point to the existing static directory
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # D:\CSMS\csm\static
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

# JAZZMIN_SETTINGS = {
#     # title of the window (Will default to current_admin_site.site_title if absent or None)
#     "site_title": "Sile Sra",
   
#     # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
#     "site_header": "SileSira",

#     # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
#     "site_brand": "SileSra",

#     # Logo to use for your site, must be present in static files, used for brand on top left
#     "site_logo": "images/logo.png",

#     # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
#     "login_logo":  "images/loginlogo.jpg",
#     "site_logo_classes": "img-circle",
#     "welcome_sign": "Welcome to SileSra",
#     "copyright": "SileSra",
#     "show_sidebar": True,
#      "hide_apps": ["Groups"],
#     # Whether to aut expand the menu
#     "navigation_expanded": False,
#     "use_google_fonts_cdn": True,
#     'CUSTOM_CSS': 'css/custom.css', 
#     # "show_ui_builder": False,
  
#     # "theme": "simplex",
  
#     "button_classes": {
#         "primary": "btn-outline-primary",
#         "secondary": "btn-outline-secondary",
#         "info": "btn-info",
#         "warning": "btn-warning",
#         "danger": "btn-danger",
#         "success": "btn-success"
#     } 
# }
# JAZZMIN_UI_TWEAKS = {
#     "navbar_small_text": False,
#     "footer_small_text": False,
#     "body_small_text": False,
#     "brand_small_text": False,
#     "brand_colour": "navbar-light",
#     "accent": "accent-primary",
#     "navbar": "navbar-light bg-light",
#     "no_navbar_border": False,
#     "navbar_fixed": False,
#     "layout_boxed": False,
#     "footer_fixed": False,
#     "sidebar_fixed": False,
#     "sidebar": "sidebar-light-primary",
#     "sidebar_nav_small_text": False,
#     "sidebar_disable_expand": False,
#     "sidebar_nav_child_indent": True,
#     "sidebar_nav_compact_style": False,
#     "sidebar_nav_legacy_style": False,
#     "sidebar_nav_flat_style": False,
#     "theme": "materia",
#     "dark_mode_theme": None,
#     "button_classes": {
#         "primary": "btn-outline-primary",
#         "secondary": "btn-outline-secondary",
        
#         "warning": "btn-warning",
#         "danger": "btn-danger",
#         "success": "btn-success"
#     }
# }
JAZZMIN_SETTINGS = {
    "site_title": "Sile Sra Admin",
    "site_header": "Sile Sra",
    "site_brand": "Sile Sra",
    "site_logo": "images/logo.png",
    "login_logo": "images/loginlogo.jpg",
    "site_logo_classes": "img-fluid rounded-circle",
    "welcome_sign": "Welcome to Sile Sra Admin Panel",
    "copyright": "© 2025 Sile Sra",
    "show_sidebar": True,
    "hide_apps": ["auth.Group"],  # Updated to include the correct full app name
    "navigation_expanded": True,
    "use_google_fonts_cdn": True,
    "custom_css": "css/custom.css",
    "theme": "lux",  # Modern and professional theme
    "show_ui_builder": False,
    "changeform_format": "collapsible",  # Makes forms easier to work with
    "changeform_format_overrides": {"auth.user": "carousel"},  # Example: customized format for specific models

    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success"
    }
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-light bg-primary",  # Clean primary color for branding
    "accent": "accent-primary",  # Consistent with the brand color
    "navbar": "navbar-dark bg-primary",  # A bold, modern dark navbar
    "no_navbar_border": True,
    "navbar_fixed": True,  # Fixes the navbar for better UX
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,  # Fixes the sidebar for easier navigation
    "sidebar": "sidebar-dark-primary",  # Matches the navbar for consistency
    "sidebar_nav_small_text": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,  # Indents child elements for clarity
    "sidebar_nav_compact_style": True,  # Compact and clean sidebar design
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",  # Alternative modern light theme
    "dark_mode_theme": "cyborg",  # Alternative bold and modern dark theme
  "button_classes": {
    "primary": "btn-primary btn-sm rounded-pill shadow-sm",
    "secondary": "btn-secondary btn-sm rounded-pill shadow-sm",
    "info": "btn-info btn-sm rounded-pill shadow-sm",
    "warning": "btn-outline-warning btn-sm rounded-pill shadow-sm",
    "danger": "btn-outline-danger btn-sm rounded-pill shadow-sm",
    "success": "btn-outline-success btn-sm rounded-pill shadow-sm"
}

}


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = '/admin/'
MEDIA_URL = '/media/'

# if you need to block access from postman make true 
CSRF_COOKIE_HTTPONLY = False
CSRF_TRUSTED_ORIGINS = [
    'http://188.245.105.29',
]
