# Generated by Django 5.0.6 on 2025-01-24 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('itemcommonproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.itemcommonproperty')),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(default=0)),
                ('mileage', models.CharField(blank=True, max_length=255, null=True)),
                ('fuelType', models.CharField(choices=[('electric', 'electric'), ('hybrid', 'hybrid'), ('petrol', 'petrol'), ('diseal', 'diseal')], max_length=255)),
                ('carType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='products.cartype')),
            ],
            bases=('products.itemcommonproperty',),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('itemcommonproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.itemcommonproperty')),
                ('numberofBedrooms', models.IntegerField(default=0)),
                ('numberofBathrooms', models.IntegerField(default=0)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('houseType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='products.housetype')),
            ],
            bases=('products.itemcommonproperty',),
        ),
    ]
