# Generated by Django 5.0.6 on 2025-01-25 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('products', '0002_servicecommonproperty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='otherItem',
            fields=[
                ('itemcommonproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.itemcommonproperty')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('products.itemcommonproperty',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('itemcommonproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.itemcommonproperty')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('products.itemcommonproperty',),
        ),
    ]
