# Generated by Django 5.0.6 on 2025-01-25 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_otheritem_service'),
        ('products', '0003_delete_serviceorbusinesstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrBusinesstype',
            fields=[
                ('servicecommonproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.servicecommonproperty')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            bases=('products.servicecommonproperty',),
        ),
    ]
