# Generated by Django 5.0.6 on 2025-01-26 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SilesraBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CBE', 'Commercial Bank of Ethiopia'), ('Awash', 'Awash Bank'), ('Dashen', 'Dashen Bank')], max_length=255)),
                ('account_number', models.CharField(max_length=255, unique=True)),
                ('bank_icon', models.ImageField(blank=True, help_text="Upload the bank's icon", null=True, upload_to='bank_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_call_number', models.CharField(blank=True, help_text='Customer service phone number', max_length=255, null=True)),
                ('Default_bank_account', models.ForeignKey(help_text='Default bank account for payments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_settings', to='setting.silesrabankaccount')),
            ],
        ),
    ]
