# Generated by Django 5.0.6 on 2025-02-01 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusienssOrServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='carMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('bank_icon', models.ImageField(blank=True, help_text="Upload the bank's icon", null=True, upload_to='bank_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='OtherItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SilesraBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Commercial Bank of Ethiopia', 'Commercial Bank of Ethiopia'), ('Dashen Bank', 'Dashen Bank'), ('Awash Bank', 'Awash Bank'), ('Enat Bank', 'Enat Bank'), ('Wegagen Bank', 'Wegagen Bank'), ('Abay Bank', 'Abay Bank'), ('Amhara Bank', 'Amhara Bank'), ('Abyssinia Bank', 'Abyssinia Bank'), ('Birhan Bank', 'Birhan Bank'), ('Cooperative Bank of Ormoia', 'Cooperative Bank of Ormoia'), ('Addis International Bank', 'Addis International Bank'), ('Gedaa Bank', 'Gedaa Bank'), ('Siinqee Bank', 'Siinqee Bank'), ('Nib Bank', 'Nib Bank'), ('Ahadu Bank', 'Ahadu Bank'), ('Bunna Bank', 'Bunna Bank'), ('Hibret Bank', 'Hibret Bank'), ('Lion Bank', 'Lion Bank'), ('Global Bank Ethiopia', 'Global Bank Ethiopia'), ('Zemen Bank', 'Zemen Bank'), ('Hijra Bank', 'Hijra Bank'), ('Zamzam Bank', 'Zamzam Bank'), ('Tsedey Bank', 'Tsedey Bank'), ('Tsehay Bank', 'Tsehay Bank')], max_length=255)),
                ('account_number', models.CharField(max_length=255, unique=True)),
                ('bank_icon', models.ImageField(blank=True, help_text="Upload the bank's icon", null=True, upload_to='bank_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_call_number', models.CharField(blank=True, help_text='Customer service phone number', max_length=255, null=True)),
                ('Default_bank_account', models.ForeignKey(help_text='Default bank account for payments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GeneralSetting', to='setting.silesrabankaccount')),
            ],
        ),
    ]
